runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4

env_variables:
  GCE_SESSION_BUCKET: "your-bucket"
  GCS_AUTH_FILE: "auth.json"
  